services:
    db:
        image: postgres:16.4
        container_name: magdala-db
        ports:
            - "127.0.0.1:5432:5432"
        environment:
            POSTGRES_USER: magdala
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB:  magdala
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: unless-stopped
        networks:
            - magdala-network
    
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                DATABASE_URL: ${DATABASE_URL}
                AUTH_SECRET: ${AUTH_SECRET}
                NEXTAUTH_URL: ${NEXTAUTH_URL}
                AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
        container_name: magdala-app
        ports:
            - "127.0.0.1:3000:3000"
        environment:
            DATABASE_URL: ${DATABASE_URL}
            AUTH_SECRET: ${AUTH_SECRET}
            NEXTAUTH_URL: ${NEXTAUTH_URL}
            AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
            NODE_ENV: production
        depends_on:
            - db
        restart: unless-stopped
        networks:
            - magdala-network


    adminer:
        image: adminer:4.8.1
        container_name: magdala-adminer
        ports:
            - "127.0.0.1:8080:8080"
        depends_on:
            - db
        restart: unless-stopped
        networks:
            - magdala-network
    
volumes:
    pgdata:

networks:
    magdala-network:
        driver: bridge